// <auto-generated />
// Source: xpoint-network-v1.registry.json, registry generation 1.
// Runtime activation intentionally remains false in the normative registry.
#nullable enable

namespace Deep.Protocol.XPointNetworkV1;

internal static class XPointNetworkRegistry
{
    internal const string SourceFileName = "xpoint-network-v1.registry.json";
    internal const int RegistryGeneration = 1;
    internal const bool RuntimeActivation = false;
    internal const int HeaderBytes = 12;
    internal const int FieldHeaderBytes = 8;
    internal const int MaximumRecordBytes = 65_535;
    internal const ushort IdentitySuite = 0x0001;
    internal const ushort NetworkSuite = 0x0201;
    internal const byte CallRelayRoleId = 4;

    internal const string XnaRootDomain = "Deep/XPoint/V1/XNA1/root";
    internal const string XnaCoreDomain = "Deep/XPoint/V1/XNA1/authority-core";
    internal const string DirectoryWitnessPolicyDomain = "Deep/XPoint/V1/directory-witness-policy";
    internal const string XvpRootDomain = "Deep/XPoint/V1/XVP1/root";
    internal const string XvpCoreDomain = "Deep/XPoint/V1/XVP1/policy-core";
    internal const string XndSignatureDomain = "Deep/XPoint/V1/XND1";
    internal const string XndCoreDomain = "Deep/XPoint/V1/XND1/core";
    internal const string FailureDomainDomain = "Deep/XPoint/V1/XND1/failure-domain";
    internal const string XnvSignatureDomain = "Deep/XPoint/V1/XNV1";
    internal const string XnvCoreDomain = "Deep/XPoint/V1/XNV1/core";
    internal const string XnhSignatureDomain = "Deep/XPoint/V1/XNH1";
    internal const string XnhCoreDomain = "Deep/XPoint/V1/XNH1/core";
    internal const string XnpExactDomain = "Deep/XPoint/V1/XNP1/exact";
    internal const string XnfRootDomain = "Deep/XPoint/V1/XNF1/root";
    internal const string XnfCoreDomain = "Deep/XPoint/V1/XNF1/core";
    internal const string NfpExactDomain = "Deep/XPoint/V1/NFP1/exact";
    internal const string XcdSignatureDomain = "Deep/XPoint/V1/XCD1";
    internal const string XcdReplicaPopDomain = "Deep/XPoint/V1/XCD1/replica-pop";
    internal const string XcdCoreDomain = "Deep/XPoint/V1/XCD1/core";

    internal static IReadOnlyList<string> AllDomains { get; } =
    [
        XnaRootDomain, XnaCoreDomain, DirectoryWitnessPolicyDomain, XvpRootDomain, XvpCoreDomain,
        XndSignatureDomain, XndCoreDomain, FailureDomainDomain, XnvSignatureDomain, XnvCoreDomain,
        XnhSignatureDomain, XnhCoreDomain, XnpExactDomain, XnfRootDomain, XnfCoreDomain, NfpExactDomain,
        XcdSignatureDomain, XcdReplicaPopDomain, XcdCoreDomain,
    ];

    private static XPointFieldDefinition B(ushort t, string n, int l, bool nz = false, ushort z = 0) =>
        new(t, n, XPointFieldKind.Bytes, l, l, NonZero: nz, ZeroIffGenerationTag: z);
    private static XPointFieldDefinition U8(ushort t, string n, ulong min = 0, ulong max = byte.MaxValue, params ulong[] values) =>
        new(t, n, XPointFieldKind.UInt8, 1, 1, min, max, AllowedValues: values.Length == 0 ? null : values);
    private static XPointFieldDefinition U16(ushort t, string n, ulong min = 0, ulong max = ushort.MaxValue, params ulong[] values) =>
        new(t, n, XPointFieldKind.UInt16, 2, 2, min, max, AllowedValues: values.Length == 0 ? null : values);
    private static XPointFieldDefinition U32(ushort t, string n, ulong min = 0, ulong max = uint.MaxValue, params ulong[] values) =>
        new(t, n, XPointFieldKind.UInt32, 4, 4, min, max, AllowedValues: values.Length == 0 ? null : values);
    private static XPointFieldDefinition U64(ushort t, string n, ulong min = 0, ulong max = ulong.MaxValue) =>
        new(t, n, XPointFieldKind.UInt64, 8, 8, min, max);
    private static XPointFieldDefinition L(ushort t, string n, ushort count, int width, int min, int max, bool nz = false) =>
        new(t, n, XPointFieldKind.FixedList, checked(width * min), checked(width * max), CountTag: count, EntryBytes: width, NonZero: nz);
    private static XPointFieldDefinition C(ushort t, string n, string magic) =>
        new(t, n, XPointFieldKind.CoreReference, 38, 38, ReferenceMagic: magic, NonZero: true);
    private static XPointFieldDefinition A(ushort t, string n, string magic) =>
        new(t, n, XPointFieldKind.ArtifactReference, 38, 38, ReferenceMagic: magic, NonZero: true);

    internal static XPointRecordDefinition Xna1 { get; } = D(
        XPointRecordKind.Xna1, "XNA1", IdentitySuite, 829, 5021, 18, XnaRootDomain, XnaCoreDomain, 2, 3,
        B(1,"networkId",16,true), U64(2,"authorityGeneration"), B(3,"predecessorAuthorityCoreHash",32,false,2),
        U8(4,"rootKeyCount",1,8), L(5,"rootKeyEntries",4,72,1,8), U8(6,"rootThreshold",1,8),
        U64(7,"directoryWitnessPolicyGeneration"), U16(8,"witnessIdProfile",values:[1]),
        U8(9,"witnessCount",3,32), L(10,"witnessEntries",9,104,3,32), U8(11,"witnessThreshold",2,32),
        C(12,"dts1PolicyCoreRef","DTS1"), B(13,"timeSourcePolicyHash",32,true), U32(14,"maximumWitnessUncertaintySeconds",1,30),
        U64(15,"minimumClientGeneration",1), U64(16,"issuedAt",1), U64(17,"notBefore",1), U64(18,"expiresAt",1),
        U8(19,"rootSignatureCount",1,8), L(20,"rootSignatures",19,96,1,8,true));

    internal static XPointRecordDefinition Xvp1 { get; } = D(
        XPointRecordKind.Xvp1, "XVP1", IdentitySuite, 450, 1122, 18, XvpRootDomain, XvpCoreDomain, 2, 3,
        B(1,"networkId",16,true), U64(2,"policyGeneration"), B(3,"predecessorPolicyCoreHash",32,false,2),
        U16(4,"enabledRoleMask",values:[31]), U8(5,"requiredOnionHopCount",values:[3]), U8(6,"mailboxReplicaCount",2,5),
        U16(7,"routeConstraintMask",15,127), U8(8,"maximumEntryGuardCandidates",values:[3]),
        U32(9,"minimumConfirmedGuardRetentionSeconds",values:[2_592_000]), U16(10,"maximumCircuitLifetimeSeconds",60,3600),
        U16(11,"mailboxProjectionProfile",values:[1]), U64(12,"requiredPmt2Generation"), C(13,"xcc1CoreRef","XCC1"),
        U16(14,"minimumActiveCarrierBindingCount",1,512), U64(15,"issuedAt",1), U64(16,"notBefore",1), U64(17,"expiresAt",1),
        C(18,"authorizingXnaCoreRef","XNA1"), U8(19,"rootSignatureCount",1,8), L(20,"rootSignatures",19,96,1,8,true));

    internal static XPointRecordDefinition Xnd1 { get; } = D(
        XPointRecordKind.Xnd1, "XND1", NetworkSuite, 1025, 3409, 36, XndSignatureDomain, XndCoreDomain, 3, 4,
        B(1,"networkId",16,true), B(2,"nodeId",32,true), U64(3,"descriptorGeneration"), B(4,"predecessorDescriptorCoreHash",32,false,3),
        B(5,"nodeIdentityEd25519PublicKey",32,true), B(6,"stakingIdentityHash",32,true), B(7,"operatorId",32,true),
        B(8,"hostId",32,true), B(9,"providerId",32,true), U32(10,"asn"), U16(11,"jurisdiction"), B(12,"failureDomainHash",32,true),
        U16(13,"roleMask",1,31), U32(14,"entryConcurrentSessionCapacity"), U64(15,"relayBytesPerSecondCapacity"),
        U64(16,"mailboxStoredBytesCapacity"), U64(17,"blobStoredBytesCapacity"), U32(18,"callConcurrentAllocationCapacity"),
        U8(19,"peerOriginCount",1,16), L(20,"peerOriginEntries",19,148,1,16), U64(21,"currentOnionKeyEpoch",1),
        B(22,"currentOnionX25519PublicKey",32,true), U64(23,"currentOnionKeyNotBefore",1), U64(24,"currentOnionKeyExpiresAt",1),
        U64(25,"nextOnionKeyEpoch",2), B(26,"nextOnionX25519PublicKey",32,true), U64(27,"nextOnionKeyNotBefore",1),
        U64(28,"nextOnionKeyExpiresAt",1), U16(29,"minimumProtocolGeneration",1), U16(30,"maximumProtocolGeneration",1),
        U8(31,"roleKeyCount",1,5), L(32,"roleKeyEntries",31,41,1,5,true), U64(33,"issuedAt",1), U64(34,"notBefore",1),
        U64(35,"expiresAt",1), U16(36,"minimumReader",1), B(37,"nodeIdentitySignature",64,true));

    internal static XPointRecordDefinition Xnv1 { get; } = D(
        XPointRecordKind.Xnv1, "XNV1", NetworkSuite, 821, 63709, 22, XnvSignatureDomain, XnvCoreDomain, 2, 3,
        B(1,"networkId",16,true), U64(2,"viewGeneration"), B(3,"predecessorViewCoreHash",32,false,2), B(4,"finalizedChainId",32,true),
        U64(5,"finalizedBlockHeight"), B(6,"finalizedBlockHash",32,true), C(7,"authorizingXnaCoreRef","XNA1"),
        B(8,"directoryWitnessPolicyHash",32,true), C(9,"activeXvpCoreRef","XVP1"), U16(10,"maturityLevel",values:[1,2,3]),
        U16(11,"nodeDescriptorCount",3,512), L(12,"xnd1ArtifactRefs",11,38,3,512,true), U16(13,"revokedNodeCount",0,512),
        L(14,"revokedNodeIds",13,32,0,512,true), U16(15,"serviceDescriptorCount",0,128), L(16,"serviceCoreRefs",15,38,0,128,true),
        U16(17,"carrierBindingCount",1,512), L(18,"xcb1ArtifactRefs",17,38,1,512,true), U64(19,"issuedAt",1),
        U64(20,"notBefore",1), U64(21,"expiresAt",1), U16(22,"minimumReader",1), U8(23,"witnessCount",2,32),
        L(24,"witnessSignatures",23,96,2,32,true));

    internal static XPointRecordDefinition Xnh1 { get; } = D(
        XPointRecordKind.Xnh1, "XNH1", NetworkSuite, 564, 5492, 14, XnhSignatureDomain, XnhCoreDomain, 2, 3,
        B(1,"networkId",16,true), U64(2,"logGeneration"), B(3,"predecessorHeadCoreHash",32,false,2), U64(4,"treeSize",1),
        B(5,"rfc6962Root",32,true), C(6,"latestXnvCoreRef","XNV1"), U64(7,"latestXnvGeneration"), C(8,"authorizingXnaCoreRef","XNA1"),
        B(9,"directoryWitnessPolicyHash",32,true), U64(10,"validFrom",1), U64(11,"validUntil",1), U16(12,"minimumReader",1),
        U8(13,"predecessorConsistencyNodeCount",0,64), L(14,"predecessorConsistencyNodes",13,32,0,64,true),
        U8(15,"witnessCount",2,32), L(16,"witnessSignatures",15,96,2,32,true));

    internal static XPointRecordDefinition Xnp1 { get; } = D(
        XPointRecordKind.Xnp1, "XNP1", NetworkSuite, 424, 4520, 0, null, XnpExactDomain, 0, 0,
        B(1,"networkId",16,true), C(2,"sourceXnhCoreRef","XNH1"), U64(3,"sourceTreeSize",1), B(4,"sourceRoot",32,true),
        C(5,"sourceLatestXnvCoreRef","XNV1"), U64(6,"sourceViewGeneration"), C(7,"targetXnhCoreRef","XNH1"),
        U64(8,"targetTreeSize",1), B(9,"targetRoot",32,true), C(10,"targetXnvCoreRef","XNV1"), U64(11,"targetViewGeneration"),
        U16(12,"proofAlgorithm",values:[1]), U64(13,"targetLeafIndex"), U8(14,"inclusionNodeCount",0,64),
        L(15,"inclusionNodes",14,32,0,64,true), U8(16,"consistencyNodeCount",0,64), L(17,"consistencyNodes",16,32,0,64,true));

    internal static XPointRecordDefinition Xnf1 { get; } = D(
        XPointRecordKind.Xnf1, "XNF1", IdentitySuite, 545, 1217, 13, XnfRootDomain, XnfCoreDomain, 2, 3,
        B(1,"networkId",16,true), U64(2,"checkpointGeneration"), B(3,"predecessorCheckpointCoreHash",32,false,2),
        B(4,"coveredGenerationRange",16), U64(5,"coveredHeadCount",1,65536), B(6,"coveredHeadMerkleRoot",32,true),
        C(7,"targetXnvCoreRef","XNV1"), B(8,"targetXnvGenerationAndHash",40,true), C(9,"targetXnhCoreRef","XNH1"),
        B(10,"targetXnhTreeSizeAndRoot",40,true), C(11,"authorizingXnaCoreRef","XNA1"), U64(12,"issuedAt",1),
        U16(13,"minimumReader",1), U8(14,"rootSignatureCount",1,8), L(15,"rootSignatures",14,96,1,8,true));

    internal static XPointRecordDefinition Nfp1 { get; } = D(
        XPointRecordKind.Nfp1, "NFP1", NetworkSuite, 445, 7281, 0, null, NfpExactDomain, 0, 0,
        B(1,"networkId",16,true), U64(2,"sourceXnvGeneration"), C(3,"sourceXnvCoreRef","XNV1"), U64(4,"sourceXnhTreeSize",1),
        B(5,"sourceXnhRoot",32,true), U64(6,"sourceLeafIndex"), C(7,"targetXnvCoreRef","XNV1"), C(8,"targetXnhCoreRef","XNH1"),
        U8(9,"xnaAuthorityChainCount",1,64), L(10,"xnaAuthorityCoreRefs",9,38,1,64,true), U8(11,"xnfCheckpointCount",1,64),
        L(12,"xnfCheckpointCoreRefs",11,38,1,64,true), U8(13,"sourceMembershipNodeCount",0,64),
        L(14,"sourceMembershipNodes",13,32,0,64,true), C(15,"liveDtt1CoreRef","DTT1"), U16(16,"proofAlgorithm",values:[1]));

    internal static XPointRecordDefinition Xcd1 { get; } = D(
        XPointRecordKind.Xcd1, "XCD1", NetworkSuite, 818, 2018, 20, XcdSignatureDomain, XcdCoreDomain, 3, 4,
        B(1,"networkId",16,true), B(2,"callRelayNodeId",32,true), U64(3,"descriptorGeneration"),
        B(4,"predecessorDescriptorCoreHash",32,false,3), B(5,"relayTargetAuthEd25519PublicKey",32,true),
        U64(6,"relayTargetAuthKeyGeneration"), U8(7,"replicaCount",2,8), L(8,"replicaEntries",7,200,2,8,true),
        U8(9,"receiptQuorum",values:[2]), U16(10,"supportedMediaSuite",values:[1]), U16(11,"supportedCmd1Version",values:[1]),
        U16(12,"supportedDtlsVersion",values:[1]), U16(13,"maximumDatagramBytes",576,1200),
        U32(14,"maximumBitrateBitsPerSecond",32000,20000000), U32(15,"maximumConcurrentAllocations",1,1000000),
        U16(16,"allocationLifetimeSeconds",1,600), U16(17,"interNodeTransportMask",1,3), U64(18,"issuedAt",1),
        U64(19,"notBefore",1), U64(20,"expiresAt",1), B(21,"callRelayRoleSignature",64,true));

    internal static IReadOnlyList<XPointRecordDefinition> All { get; } =
        [Xna1, Xvp1, Xnd1, Xnv1, Xnh1, Xnp1, Xnf1, Nfp1, Xcd1];

    internal static XPointRecordDefinition Get(string magic) => magic switch
    {
        "XNA1" => Xna1, "XVP1" => Xvp1, "XND1" => Xnd1, "XNV1" => Xnv1,
        "XNH1" => Xnh1, "XNP1" => Xnp1, "XNF1" => Xnf1, "NFP1" => Nfp1,
        "XCD1" => Xcd1,
        _ => throw new XPointValidationException(XPointValidationStage.Header, "UnknownMagic", "Unknown XPoint Network V1 magic."),
    };

    private static XPointRecordDefinition D(
        XPointRecordKind kind, string magic, ushort suite, int min, int max,
        int unsignedLastTag, string? signatureDomain, string hashDomain,
        int generationTag, int predecessorHashTag, params XPointFieldDefinition[] fields) =>
        new(kind, magic, 1, suite, min, max, fields, unsignedLastTag,
            signatureDomain, hashDomain, generationTag, predecessorHashTag);
}
