// Generated by eng/Generate-DeepMlKemApprovedAssets.ps1 from approved build evidence.
// Do not edit by hand; run the generator and commit the resulting diff.
namespace Deep.Protocol.MessagingCrypto;

internal sealed record DeepMlKemApprovedAsset(
    string RuntimeIdentifier,
    string RelativePath,
    long Bytes,
    string Sha256,
    string Abi);

internal static class DeepMlKemApprovedAssets
{
    internal const string ManifestProviderIdentifier = "mlkem-native/v2.0.0/portable-c/deep-abi-v1";

    internal static DeepMlKemApprovedAsset WindowsX64 { get; } = new(
        "win-x64",
        "runtimes/win-x64/native/deep_mlkem.dll",
        131584,
        "d682595f4f88d18a1a3039319d22cc06aaaa706c851ec717b06b6e45d42b2f45",
        ManifestProviderIdentifier);

    internal static DeepMlKemApprovedAsset ForCurrentProcess()
    {
        if (OperatingSystem.IsWindows() &&
            System.Runtime.InteropServices.RuntimeInformation.ProcessArchitecture ==
            System.Runtime.InteropServices.Architecture.X64)
            return WindowsX64;

        throw new PlatformNotSupportedException(
            "No release-approved Deep ML-KEM asset exists for the current process RID.");
    }
}
