// Generated by eng/Generate-DeepMlKemApprovedAssets.ps1 from approved build evidence.
// Do not edit by hand; run the generator and commit the resulting diff.
namespace Deep.Protocol.MessagingCrypto;

internal sealed record DeepMlKemApprovedAsset(
    string RuntimeIdentifier,
    string RelativePath,
    long Bytes,
    string Sha256,
    string Abi);

internal static class DeepMlKemApprovedAssets
{
    internal const string ManifestProviderIdentifier = "mlkem-native/v2.0.0/portable-c/deep-abi-v1";

    internal static DeepMlKemApprovedAsset WindowsX64 { get; } = new(
        "win-x64",
        "runtimes/win-x64/native/deep_mlkem.dll",
        131584,
        "462a80feda563b30312e836cad108923eeed0aa16ce1365de7a8506d389af8eb",
        ManifestProviderIdentifier);

    internal static DeepMlKemApprovedAsset WindowsArm64 { get; } = new(
        "win-arm64",
        "runtimes/win-arm64/native/deep_mlkem.dll",
        123904,
        "cd27e3c716a1b3cf4123f909e7d03861423becd8799a4abceb37f7f359d092f7",
        ManifestProviderIdentifier);

    internal static DeepMlKemApprovedAsset AndroidArm64 { get; } = new(
        "android-arm64",
        "runtimes/android-arm64/native/libdeep_mlkem.so",
        67576,
        "5528f0ff05cbda00bdcd648ef72dcc870c3dde3535aa5f77457b554e93261fa5",
        ManifestProviderIdentifier);

    internal static DeepMlKemApprovedAsset ForCurrentProcess()
    {
        if (OperatingSystem.IsWindows() &&
            System.Runtime.InteropServices.RuntimeInformation.ProcessArchitecture ==
            System.Runtime.InteropServices.Architecture.X64)
            return WindowsX64;

        if (OperatingSystem.IsWindows() &&
            System.Runtime.InteropServices.RuntimeInformation.ProcessArchitecture ==
            System.Runtime.InteropServices.Architecture.Arm64)
            return WindowsArm64;

        if (OperatingSystem.IsAndroid() &&
            System.Runtime.InteropServices.RuntimeInformation.ProcessArchitecture ==
            System.Runtime.InteropServices.Architecture.Arm64)
            return AndroidArm64;

        throw new PlatformNotSupportedException(
            "No release-approved Deep ML-KEM asset exists for the current process RID.");
    }
}
