param(
    [Parameter(Mandatory = $true)][string]$RegistryPath,
    [Parameter(Mandatory = $true)][string]$OutputPath
)

$ErrorActionPreference = 'Stop'
$registry = Get-Content -LiteralPath $RegistryPath -Raw | ConvertFrom-Json
$lines = @($registry.recovery.schemaProfileSourceLines)
if ($lines.Count -ne 26) { throw "Expected exactly 26 recovery schema profile lines." }
$payload = [Text.Encoding]::UTF8.GetBytes(($lines -join "`n") + "`n")
if ($payload.Length -ne 72345) { throw "Unexpected recovery schema profile payload length $($payload.Length)." }
$escaped = $lines | ForEach-Object {
    '        "' + $_.Replace('\', '\\').Replace('"', '\"') + '",'
}
$source = @(
    '// <auto-generated />'
    'namespace Deep.Protocol.DeepNative;'
    ''
    'internal static class RecoverySchemaProfile'
    '{'
    '    internal static readonly string[] SourceLines ='
    '    ['
    $escaped
    '    ];'
    '}'
    ''
) -join "`n"
[IO.File]::WriteAllText($OutputPath, $source, [Text.UTF8Encoding]::new($false))
